version: '3'

services:
  worker:
    build: ./worker
    container_name: worker
    env_file:
      - .env

  api:
    build: ./api
    container_name: api
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - '8080:8080'
    networks:
      - db
    env_file:
      - .env

  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1412
      POSTGRES_DB: robbo
    volumes:
      - db-data:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge


volumes:
  db-data: